name: chatgpt_flutter
description: A Flutter package for interacting with OpenAI API's (GPT-3). Easily integrate OpenAI's powerful AI models into your application.
version: 1.0.0
homepage: https://github.com/HarryJackson96/chatgpt_flutter

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.1.1  
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

flutter:
