name: build

on: 
  push: 
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.11'
          channel: 'stable'

      - name: Get all Flutter Packages
        run: flutter pub get

      - name:
        run: flutter --version

      - name: Analyze
        run: flutter analyze

      - name: Run Flutter Test
        run: flutter test


